In [1]:
# Importando as bibliotecas para trabalhar com redes neurais
from keras.models import Sequential
from keras.layers import Dense

In [2]:
# Importando as bibliotecas necessárias
import numpy as np
import pandas as pd

# Dataset Iris
from sklearn.datasets import load_iris

# Ferramentas de pré processamento
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [3]:
# Carregando o conjunto de dados Iris
iris = load_iris()
X = iris.data
y = iris.target

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
# Pré-processamento dos dados
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [6]:
X_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [7]:
# Dividindo em conjunto de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [9]:
# Codificando as variáveis de saída (target)
encoder = OneHotEncoder(categories='auto')
y_train_encoded = encoder.fit_transform(y_train.reshape(-1, 1)).toarray()
y_test_encoded = encoder.transform(y_test.reshape(-1, 1)).toarray()

In [12]:
y_train_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1

In [13]:
# Criando o modelo de rede neural
model = Sequential()

# A camada de entrada terá:
# A primeira camada oculta terá:
model.add(Dense(10, input_shape=(4,), activation='relu'))

# A segunda camada terá:
model.add(Dense(8, activation='relu'))

# A camada de saída terá:
model.add(Dense(3, activation='softmax'))

In [14]:
# Compilando o modelo
# optmizer ---> Otimizador
# loss ---> Função de custo (Loss Function)

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [37]:
# Treinando o modelo
# Epochs ---> épocas de treinamento
model.fit(X_train, y_train_encoded, epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 8ms/step - loss: 0.0396 - accuracy: 0.9833
Epoch 2/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0397 - accuracy: 0.9833
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0398 - accuracy: 0.9833
Epoch 4/100
4/4 [==============================] - 0s 6ms/step - loss: 0.0399 - accuracy: 0.9833
Epoch 5/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0398 - accuracy: 0.9833
Epoch 6/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0397 - accuracy: 0.9833
Epoch 7/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0398 - accuracy: 0.9833
Epoch 8/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0399 - accuracy: 0.9833
Epoch 9/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0400 - accuracy: 0.9833
Epoch 10/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0399 - accuracy: 0.9833
Epoch 11/100
4/4 [===========

In [36]:
# Avaliando o modelo
loss, accuracy = model.evaluate(X_test, y_test_encoded)
print(f'Acurácia do modelo: {accuracy}')

1/1 [==============================] - 0s 91ms/step - loss: 0.0886 - accuracy: 0.9667
Acurácia do modelo: 0.9666666388511658
